 version: '3.8'
 services:
  web:
    build: .
    container_name: react_website
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules